In [97]:
# Task 1  Write a program that allow you to enter 4 numbers and stores them in a file called "Numbers" 
my_file = open("Numbers.txt","w")
my_file.write("* 3 \n* 45 \n* 83\n* 21\n")
my_file.close()

In [ ]:
# Task 2 Write a program to ask a student for their percentage mark and convert this to a grade.
# The conversion will be done in a functin called mark_grade

# I have to think about this one and I'll sent it in homework for next week. Thank you!

In [11]:
# 1. Create a 1D array of numbers from 0 to 9

import numpy as np
array = np.array([0,1,2,3,4,5,6,7,8,9])
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
array = np.arange (0,10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [36]:
# 2. Create a 3x3 NumPy array of a Boolean value Trues
# array = np.array([true,])
a = np.ones((9),dtype=bool).reshape(3,3)
print(a)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [50]:
b = np.zeros((3,3),dtype=bool)
print(b)

[[False False False]
 [False False False]
 [False False False]]


In [13]:
# 3. Extract all odd numbers from array of 1-10 
a = np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [44]:
# 4. Replace all odd numbers in a array of 1-10 with a value -1
array = np.arange(1,10)
odd_number = np.where(array%2 == 1)
array[odd_number] = -1
print(array)

[-1  2 -1  4 -1  6 -1  8 -1]


In [45]:
# 5. Convert a 1D array to a 2D array with 2 rows
a = np.arange(1,11)
print(a)
reshape_a = np.arange(1,11).reshape(2,5)
print(reshape_a)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [16]:
# 6. Create two arrays a and b, stack these two arrays vertically use the np.dot and np.sum to calculate totats
a = np.arange(0,9).reshape(3,3)
b = np.arange(10,19).reshape(3,3)
c =np.vstack((a,b))
print(c)
dot = np.dot(a,b)
sum = np.sum(dot)
print(dot)
print(sum)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[[ 45  48  51]
 [162 174 186]
 [279 300 321]]
1566


In [96]:
#extension1 
#list1 = np.ones((1,3), dtype=int)
#list2 = list1 + list1
#list3 = list1 * 3
#list4 = np.arange(1,4)
list1 = np.ones(3)
list2 = list1 + list1
list3 = list2 + list1
list4 = np.arange(1,4)
print(list1)
print(list2)
print(list3)
print(list4)


pattern = np.concatenate((list1 , list2, list3, list4, list4, list4))
print(pattern)

tile = np.tile(list4, 3)
pattern_tile = np.concatenate((list1 , list2, list3, tile))
print(pattern_tile)


[1. 1. 1.]
[2. 2. 2.]
[3. 3. 3.]
[1 2 3]
[1. 1. 1. 2. 2. 2. 3. 3. 3. 1. 2. 3. 1. 2. 3. 1. 2. 3.]
[1. 1. 1. 2. 2. 2. 3. 3. 3. 1. 2. 3. 1. 2. 3. 1. 2. 3.]


In [56]:
list1 = np.ones(3).reshape(1,3)
print (list1)

[[1. 1. 1.]]


In [86]:
#extension2
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8,9])
new_b = (b[2:]) 
#print(new_b)
combine = np.concatenate((a,new_b))
print(combine)

[1 2 3 4 5 6 7 8 9]


In [74]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8,9])
combine = np.concatenate((a,b))
combine = np.unique(combine)

print(combine)


[1 2 3 4 5 6 7 8 9]


In [85]:
#exension3
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8,9])
new_a = (a[2:])
new_b = (b[:3])
combine = np.concatenate((new_a,new_b))
x = np.sum(combine)
print(x)



27
